# Generated by Django 2.2.2 on 2020-05-01 05:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('company', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('location', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('0', 'Full Time'), ('1', 'Part Time'), ('2', 'Temporary'), ('3', 'Free Lance'), ('4', 'Internship')], default=0, max_length=10)),
                ('no_of_vacancies', models.IntegerField(default=1)),
                ('experience', models.CharField(help_text='In years', max_length=5)),
                ('salary', models.CharField(default='Negotiable', help_text='Per Month', max_length=10)),
                ('responsibilities', models.TextField()),
                ('key_skills', models.TextField()),
                ('job_description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('last_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Category')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
