# Generated by Django 2.2.2 on 2020-06-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Temporary', 'Temporary'), ('Free Lance', 'Free Lance'), ('Internship', 'Internship')], max_length=10),
        ),
    ]
